fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    portage: "https://github.com/gentoo/puppet-portage.git"
  symlinks:
    apache: "#{source_dir}"
    site_apache: "#{source_dir}/spec/fixtures/site_apache"
